<h2>Bienvenue: <?=$prenom?> <?=$nom?></h2>
<h4>Sélectionnez l'option souhaitée</h4>
<div class="container">
  <div class="row">
    <div class="col">     
      <a href=mvc_pr/admin?adminchoice=utilisateur  class="text-muted text-decoration-none"> 
        <div class="row">
          <h2>Liste Utilisateur</h2>&nbsp;&nbsp;
          <i class="fa fa-group" style="font-size:36px;"></i>
        </div>
      </a>  
    </div>
    <div class="col">
      <a href=mvc_pr/admin?adminchoice=produit class="text-muted text-decoration-none"> 
        <div class="row">
          <h2>Liste Produits</h2>&nbsp;&nbsp;
          <i class="fa fa-puzzle-piece" style="font-size:36px;"></i>
        </div>
      </a>  
    </div>
  </div>
</div>
 
